version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - "6432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - ./storage:/var/lib/pgadmin/storage/pg_pg.ru
    environment:
      - TZ=Europe/Moscow
      - DATABASE_PASSWORD=root
      - DATABASE_USERNAME=postgres
      - DATABASE_NAME=postgres