/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AInputSearch: typeof import('ant-design-vue/es')['InputSearch']
    ATable: typeof import('ant-design-vue/es')['Table']
    LeadsTable: (typeof import('./src/feature/leads/LeadsTable.vue'))['default']
  }
}
